// <auto-generated />
using Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Final.Data.DonHang", b =>
                {
                    b.Property<int>("MaKhach")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaKhach", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("DonHangs");

                    b.HasData(
                        new
                        {
                            MaKhach = 1,
                            MaSach = 2,
                            SoLuong = 20
                        },
                        new
                        {
                            MaKhach = 2,
                            MaSach = 1,
                            SoLuong = 10
                        },
                        new
                        {
                            MaKhach = 3,
                            MaSach = 2,
                            SoLuong = 2
                        });
                });

            modelBuilder.Entity("Final.Data.KhachHang", b =>
                {
                    b.Property<int>("MaKhach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenDN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhach")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhach");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            MaKhach = 1,
                            TenDN = "DN1",
                            TenKhach = "Không Gia Đình"
                        },
                        new
                        {
                            MaKhach = 2,
                            TenDN = "DN2",
                            TenKhach = "Một món quà"
                        },
                        new
                        {
                            MaKhach = 3,
                            TenDN = "DN3",
                            TenKhach = "Tam quốc diễn nghĩa"
                        });
                });

            modelBuilder.Entity("Final.Data.LoaiSach", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSachs");

                    b.HasData(
                        new
                        {
                            MaLoai = 1,
                            TenLoai = "Trinh Thám"
                        },
                        new
                        {
                            MaLoai = 2,
                            TenLoai = "Hài Hước"
                        },
                        new
                        {
                            MaLoai = 3,
                            TenLoai = "Self-help"
                        });
                });

            modelBuilder.Entity("Final.Data.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<string>("Hinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSach")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSach");

                    b.HasIndex("MaLoai");

                    b.ToTable("Sachs");

                    b.HasData(
                        new
                        {
                            MaSach = 1,
                            DonGia = 200000,
                            Hinh = "https://vtv1.mediacdn.vn/thumb_w/650/2019/9/3/17988102-7420621-the8bookpotterseriesandotherrelatedstoriesaudiorecordi-a-61567460030727-15674958768921527956477.jpg",
                            MaLoai = 1,
                            Mota = "Harry Potter Full",
                            TenSach = "Harry Potter"
                        },
                        new
                        {
                            MaSach = 2,
                            DonGia = 350000,
                            Hinh = "https://dep.com.vn/wp-content/uploads/2018/11/khong-gia-dinh-1.jpg",
                            MaLoai = 2,
                            Mota = "Sách 1st seller",
                            TenSach = "Không Gia Đình"
                        });
                });

            modelBuilder.Entity("Final.Data.DonHang", b =>
                {
                    b.HasOne("Final.Data.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final.Data.Sach", "Sach")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("Final.Data.Sach", b =>
                {
                    b.HasOne("Final.Data.LoaiSach", "LoaiSach")
                        .WithMany("Sachs")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSach");
                });

            modelBuilder.Entity("Final.Data.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("Final.Data.LoaiSach", b =>
                {
                    b.Navigation("Sachs");
                });

            modelBuilder.Entity("Final.Data.Sach", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
